### ISSUE TITLE
Compress gif images

### ISSUE THREAD

**Issue by chrismore** [mozilla/all-aboard#74]
The animated gifs in the media folder for both the values and utility track are 1-8MB each and those are massive and contributing to the size of the XPI overall.

**Comment by schalkneethling** [comment]
Yup, I have noticed this. I compressed them as much as one can after the fact but, perhaps can have a look at improving the size of the initial files. There are some tricks, like lessening the number of tween frames and compressing the images used before they are added to the animated gif.

For the utility stream gifs, perhaps we do not have to care about high-dpi versions. In that case, Matt can simply size them to 320x220px which is half the current size. That will already make a big difference.

**Comment by schalkneethling** [comment]
I did some experimentation with gifsicle and here is the first result:

Current:
Dimensions: 640x440px
File size: 1.2MB
![content1](https://cloud.githubusercontent.com/assets/10350960/16077818/69ceefda-32fb-11e6-80f6-bd85f0f0b30a.gif)

Optimized
Dimensions: 320x220px
File size: 553kb
![content1-optimized](https://cloud.githubusercontent.com/assets/10350960/16077826/723c9a96-32fb-11e6-8880-6aec5f44de96.gif)

**Comment by FrancescoSTL** [comment]
New images:  https://www.dropbox.com/sh/xeybqk5lm84wkqq/AABIp7VP5x99UvNJWeGkw-nVa?dl=0

**Comment by FrancescoSTL** [comment]
Utility sidebars will be compressed when #107 merges

**Comment by schalkneethling** [comment]
First set of utility sidebar updates merged in https://github.com/mozilla/all-aboard/pull/107

**Comment by FrancescoSTL** [comment]
Compressing values header images is not necessary for the demo tomorrow, as they are sized correctly right now, we just want to reduce file size. Moving milestones

**Comment by chrismore** [comment]
Let's get the values header images compressed too as they are still massive: https://github.com/mozilla/all-aboard/tree/master/data/media/headers/values

**Comment by FrancescoSTL** [comment]
@schalkneethling did we ever come to a conclusion as to why the values headers load slowly? I'll ping Matt about the values headers

**Comment by schalkneethling** [comment]
@FrancescoSTL I know Matt has looked at this some, but last I heard there has been no resolution. Would be best to have a chat to him and see where we are at. Thanks!

**Comment by FrancescoSTL** [comment]
Per my convo with @ternstyles, sounds like he will attempt to record a gif of the current gif, in the way that he recorded a gif of the utility header videos. This is a pretty hacky solution, but I think it will work.

**Comment by ternstyles** [comment]
I've had some success bringing down the file size for the first 2 Values GIFs by playing with the frame rate. I can try this out on there others as well. I am still not sure why the smaller K size files were loading faster than the larger K size ones. Attached are the first 2, both below 1gb in size now. 
![moz-content_1](https://cloud.githubusercontent.com/assets/20114656/16419610/60dfe066-3d1c-11e6-90d4-e7e164884b80.gif)
![moz-content_2](https://cloud.githubusercontent.com/assets/20114656/16419613/6355c4b4-3d1c-11e6-9596-c07275bbb5a9.gif)

**Comment by FrancescoSTL** [comment]
Fixed in #188

**Comment by chrismore** [comment]
@FrancescoSTL @ternstyles I think I have an idea about why the heard and lock images still have an issue loading. They are the only images on values that are not gifs that repeat. The rest of the gifs loop back to the first frame and these don't and almost always have issues loading. Should we try making these gifs repeat and see if the issue goes away? They are still not loading right and it looks pretty bad.

**Comment by schalkneethling** [comment]
I agree @chrismore Those are definitely still problematic.

**Comment by ternstyles** [comment]
Let me know if you notice a difference with these updated GIFs below. I've played with the frame rate and also ensure that they are forever looping. All K size are below 120kb (much lower than the first two)

![moz-content_3](https://cloud.githubusercontent.com/assets/20114656/16455283/b993ccca-3de1-11e6-869c-1277e95f2a81.gif)
![moz-content_4](https://cloud.githubusercontent.com/assets/20114656/16455280/b98109e6-3de1-11e6-855f-d79b3eb4cc30.gif)
![moz-content_5](https://cloud.githubusercontent.com/assets/20114656/16455282/b9891028-3de1-11e6-9c47-509544014d0e.gif)

**Comment by FrancescoSTL** [comment]
@ternstyles thanks for the updated images. I'll create a new PR for them.

**Comment by FrancescoSTL** [comment]
@ternstyles these don't seem to be giving the same issues atm. Can you re-make them in the same way you did the first two? I am 90% sure this will fix our issue, as the file will be created in the exact same way our utility headers were.

**Comment by ternstyles** [comment]
@FrancescoSTL the above 3 are created the same way as the first 2. They have the same frame rate, forever looping, and same physical 2x dimensions.

**Comment by FrancescoSTL** [comment]
I'm stumped. @chrismore + @schalkneethling  seems as though our problem persists.

**Comment by ternstyles** [comment]
@FrancescoSTL I've attached updated Values GIFs. All are sized at 120x120px


![moz-content_1](https://cloud.githubusercontent.com/assets/20114656/16463382/988347fa-3e03-11e6-94e0-6c2e74e74bf2.gif)
![moz-content_2](https://cloud.githubusercontent.com/assets/20114656/16463384/988c1be6-3e03-11e6-9b01-2fa5768cd956.gif)
![moz-content_3](https://cloud.githubusercontent.com/assets/20114656/16463383/988a7aca-3e03-11e6-9399-7c2d56d1250a.gif)
![moz-content_4](https://cloud.githubusercontent.com/assets/20114656/16463385/988d21ee-3e03-11e6-9d16-57c7081739b5.gif)
![moz-content_5](https://cloud.githubusercontent.com/assets/20114656/16463386/9893f7b2-3e03-11e6-8151-aef2bb0b1992.gif)

**Comment by FrancescoSTL** [comment]
Merged in #207. @chrismore @fabiorios @ternstyles I believe this solved the problem, but I'll leave it to you all to prove me wrong ;). All is merged to master. I'll close when I get confirmation from one/all of you that this works.

**Comment by chrismore** [comment]
Images work for me now! r+
