### ISSUE TITLE
Error when clicking badge w/o notification present

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/all-aboard#80]
If there is no notification present on the badge (already opened the sidebar), and the sidebar is currently open, clicking the badge throws the following error: "The provided title and url combination is invalid (already used)."
<img width="854" alt="screen shot 2016-06-15 at 1 46 02 pm" src="https://cloud.githubusercontent.com/assets/9794516/16080379/77f30592-3300-11e6-806d-ca298297c30d.png">

**Comment by schalkneethling** [comment]
This is solved in https://github.com/mozilla/all-aboard/pull/81

**Comment by FrancescoSTL** [comment]
Seems as though this issue is still present before you:
A. Reach and finish the import sidebar or,
B. Exit the import sidebar

**Comment by schalkneethling** [comment]
@chrismore Can you confirm that this is resolved? Thanks!

**Comment by chrismore** [comment]
@schalkneethling this is resolved, but a new issue is noted here: https://github.com/mozilla/all-aboard/issues/76#issuecomment-226197114
